/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-25 03:56:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.kh.member.model.vo.*;
import com.kh.member.model.vo.*;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1524574374711L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1524101040852L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.kh.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    ");

    
    //Member memberLoggedIn = (Member)request.getAttribute("memberLoggedIn");
    Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
   	System.out.println("테스터스"+memberLoggedIn);
   	
   	String contextPath = request.getContextPath();
   	
   	//쿠키관련 (클라이언트가 부낸 쿠키 처리)
   	
   	Cookie[] cookies = request.getCookies();
   	//최초접속시 cookie는 null임.
   	
   	boolean saveId = false;
   	String userIdSaved = "";
   	
   	if(cookies !=null){
   		System.out.println("--------------------------------");
   		System.out.println("브라우져가 전송한 쿠키목록");
   		System.out.println("--------------------------------");
		for(Cookie c : cookies ){
			String key = c.getName();
			String value = c.getValue();
	   		System.out.println("쿠키가요 ===> " + key + " : " + value );
	   		
	   		//아이디저장 쿠키검사
	   		if("saveId".equals(key)){
	   			saveId = true;
	   			userIdSaved = value;
	   		}else{
	   			
	   		}
		}   		
   		System.out.println("--------------------------------");
   	}
   	
   String del = (String)request.getAttribute("complete");
   	
   
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hello MVC</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function fn_loginValidate(){\r\n");
      out.write("\tconsole.log(\"");
      out.print( memberLoggedIn );
      out.write("\")\r\n");
      out.write("\t//아이디\r\n");
      out.write("\tif($(\"#userId\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 검사\r\n");
      out.write("\tif($(\"#password\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t$(\"#password\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_logout(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h1>Hello MVC</h1>\r\n");
      out.write("\t\t\t<!-- 로그인시작 -->\r\n");
      out.write("\t\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t\t\t");
 if(memberLoggedIn==null) {
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"loginFrm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/member/MemberLoginServlet\" method=\"post\" onsubmit=\"return fn_loginValidate();\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"userId\" placeholder=\"아이디\" value = '");
      out.print( saveId ? userIdSaved : "" );
      out.write("' /></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password\" placeholder=\"비밀번호\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"로그인\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print(saveId ? "checked":"" );
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"saveid\">아이디저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"회원가입\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll'\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<table id=\"logged-in\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( memberLoggedIn.getUserName() );
      out.write("님, 안녕하세요.</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" value=\"내정보 보기\" onclick='location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberView?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\"'>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"로그아웃\" onclick='location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\"'></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인 끝 -->\r\n");
      out.write("\t\t\t<!-- 메인메뉴 시작 -->\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"home\"><a href=\"");
      out.print(contextPath);
      out.write("\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"notice\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/notice/noticeList\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/board/boardList\">게시판</a></li>\r\n");
      out.write("\t\t\t\t\t");
 if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getUserId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\">회원관리</a></li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/movie/onScreen\">상영등록</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/movie/regMovie\">영화등록</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"content\">");
      out.write("\r\n");
      out.write("\r\n");
 List<Member> list = (List<Member>)request.getAttribute("list"); 
	System.out.println("list@memberList.jsp="+list);
	
	String memberFiderUrl = request.getContextPath()+"/admin/memberFinder";


      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#tbl-member{border-collapse: collapse; width:100%;}\r\n");
      out.write("#tbl-member th, #tbl-member td {padding:10px; border:1px solid #bbb; font-size:14px; }\r\n");
      out.write("#tbl-member tr:hover{background:#333; color:white;}\r\n");
      out.write("#tbl-member th{}\r\n");
      out.write("#tbl-member td{}\r\n");
      out.write("#search-userId input{}\r\n");
      out.write("#search-userId button{ }\r\n");
      out.write("div#search-container{padding:3px; margin:0 0 10px 0; background:rgba(0, 188, 212, 0.3);}\r\n");
      out.write("#memberList-container input{padding:10px;}\r\n");
      out.write("#search-userId, #search-userName, div#search-Gender{}\r\n");
      out.write("div#search-userName, div#search-Gender{display:none;}\r\n");
      out.write("div#pageBar{margin-top:10px; text-align:center; background:rgba(0, 188, 212, 0.3);}\r\n");
      out.write("div#pageBar span{display:inline-block; padding:10px; background:#333; color:#fff; margin:0px 2px;}\r\n");
      out.write("div#pageBar span:hover{background:red;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#searchType\").change(function(){\r\n");
      out.write("\t\t$(\"#search-userId\").hide();\r\n");
      out.write("\t\t$(\"#search-userName\").hide();\r\n");
      out.write("\t\t$(\"#search-gender\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#search-\"+$(this).val()).css(\"display\",\"block\")\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<section id=\"memberList-container\">\r\n");
      out.write("\t<h2>회원관리</h2>\r\n");
      out.write("\t<!-- 검색영역 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"search-container\">\r\n");
      out.write("\t\t검색타입 : \r\n");
      out.write("\t\t<select name=\"searchType\" id=\"searchType\">\r\n");
      out.write("\t\t\t<option value=\"userId\">아이디</option>\r\n");
      out.write("\t\t\t<option value=\"userName\">회원명</option>\r\n");
      out.write("\t\t\t<option value=\"gender\">성별</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<div id=\"search-userId\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print( memberFiderUrl );
      out.write(" \">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"searchType\" value=\"userId\"/>\r\n");
      out.write("\t\t\t\t<input type=\"search\" name=\"searchKeyword\" id=\"\" size=\"25\" placeholder=\"검색할 아이디를 입력하세요.\" required />\r\n");
      out.write("\t\t\t\t<button type =\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"search-userName\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print( memberFiderUrl );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"searchType\" value=\"userName\" />\r\n");
      out.write("\t\t\t\t<input type=\"search\" name=\"searchKeyword\" id=\"\" size=\"25\" placeholder=\"검색할 회원명을 입력하세요.\" required />\r\n");
      out.write("\t\t\t\t<button type =\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"search-gender\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print( memberFiderUrl );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"searchType\" value=\"gender\" />\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"searchKeyword\" id=\"\" value=\"M\" checked/> 남\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"searchKeyword\" id=\"\" value=\"F\" /> 여\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button type =\"submit\">검색</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table id=\"tbl-member\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>성</th>\r\n");
      out.write("\t\t\t<th>나이</th>\r\n");
      out.write("\t\t\t<th>이메일</th>\r\n");
      out.write("\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t<th>취미</th>\r\n");
      out.write("\t\t\t<th>가입날짜</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			if(list==null || list.isEmpty()){
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"9\" align=\"center\">데이터가 존재하지 않습니다.</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t");
 }else{		
			for(Member m : list){
		
      out.write("\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=\"");
      out.print( request.getContextPath());
      out.write("/member/memberView?userId=");
      out.print(m.getUserId() );
      out.write('"');
      out.write('>');
      out.print(m.getUserId() );
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(m.getUserName()  );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print("M".equals(m.getGender()) ? "남" : "여"  );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(m.getAge()  );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(m.getEmail()  );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(m.getPhone()  );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(m.getAddress()  );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(m.getHobby()  );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(m.getEnrollDate()  );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\t \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
}
		}
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("<div id=\"pageBar\">");
      out.print(request.getAttribute("pageBar") );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;Copyright 2018. <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
