/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-04-24 12:54:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import com.kh.member.model.vo.*;

public final class memberView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1524574374711L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1524101040852L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.kh.member.model.vo");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    
    //Member memberLoggedIn = (Member)request.getAttribute("memberLoggedIn");
    Member memberLoggedIn = (Member)session.getAttribute("memberLoggedIn");
   	System.out.println("테스터스"+memberLoggedIn);
   	
   	String contextPath = request.getContextPath();
   	
   	//쿠키관련 (클라이언트가 부낸 쿠키 처리)
   	
   	Cookie[] cookies = request.getCookies();
   	//최초접속시 cookie는 null임.
   	
   	boolean saveId = false;
   	String userIdSaved = "";
   	
   	if(cookies !=null){
   		System.out.println("--------------------------------");
   		System.out.println("브라우져가 전송한 쿠키목록");
   		System.out.println("--------------------------------");
		for(Cookie c : cookies ){
			String key = c.getName();
			String value = c.getValue();
	   		System.out.println("쿠키가요 ===> " + key + " : " + value );
	   		
	   		//아이디저장 쿠키검사
	   		if("saveId".equals(key)){
	   			saveId = true;
	   			userIdSaved = value;
	   		}else{
	   			
	   		}
		}   		
   		System.out.println("--------------------------------");
   	}
   	
   String del = (String)request.getAttribute("complete");
   	
   
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Hello MVC</title>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.3.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/style.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function fn_loginValidate(){\r\n");
      out.write("\tconsole.log(\"");
      out.print( memberLoggedIn );
      out.write("\")\r\n");
      out.write("\t//아이디\r\n");
      out.write("\tif($(\"#userId\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//패스워드 검사\r\n");
      out.write("\tif($(\"#password\").val().trim().length==0){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t$(\"#password\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_logout(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<h1>Hello MVC</h1>\r\n");
      out.write("\t\t\t<!-- 로그인시작 -->\r\n");
      out.write("\t\t\t<div class=\"login-container\">\r\n");
      out.write("\t\t\t\t");
 if(memberLoggedIn==null) {
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"loginFrm\" action=\"");
      out.print(request.getContextPath() );
      out.write("/member/MemberLoginServlet\" method=\"post\" onsubmit=\"return fn_loginValidate();\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"userId\" id=\"userId\" placeholder=\"아이디\" value = '");
      out.print( saveId ? userIdSaved : "" );
      out.write("' /></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password\" placeholder=\"비밀번호\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" value=\"로그인\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"saveId\" id=\"saveId\" ");
      out.print(saveId ? "checked":"" );
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"saveid\">아이디저장</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"회원가입\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/memberEnroll'\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<table id=\"logged-in\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print( memberLoggedIn.getUserName() );
      out.write("님, 안녕하세요.</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" value=\"내정보 보기\" onclick='location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberView?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("\"'>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"로그아웃\" onclick='location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout\"'></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인 끝 -->\r\n");
      out.write("\t\t\t<!-- 메인메뉴 시작 -->\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"home\"><a href=\"");
      out.print(contextPath);
      out.write("\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"notice\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/notice/noticeList\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/board/boardList\">게시판</a></li>\r\n");
      out.write("\t\t\t\t\t");
 if(memberLoggedIn != null && "admin".equals(memberLoggedIn.getUserId())){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/memberList\">회원관리</a></li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/movie/onScreen\">상영등록</a></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"board\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/movie/regMovie\">영화등록</a></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- 메인메뉴 끝 -->\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<section id=\"content\">");
      out.write("\r\n");
      out.write("    ");


//	Member m = (Member)session.getAttribute("memberLoggedIn");
    Member m = (Member)request.getAttribute("Member");
   	String[] hobbys = m.getHobby().split(",");
   	System.out.println(hobbys);
    
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write(" \r\n");
      out.write("    </style>\r\n");
      out.write("<script>\r\n");
      out.write("function fn_validation(){\r\n");
      out.write("\t$pw = $(\"#pass_Word\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\tif($pw == \"\"){\r\n");
      out.write("\t\talert(\"비번을 입력 하세요\");\r\n");
      out.write("\t\treturn false; \r\n");
      out.write("\t}\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t$pwc = $(\"#pass_WordChk\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tif($pwc == \"\"){\r\n");
      out.write("\t\talert(\"비번 확인을 입력 하세요\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif($pw != $pwc){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(\"비밀번호가 맞지 않습니다.\")\r\n");
      out.write("\t\treturn false; \t\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true; \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write(" <form action=\"");
      out.print( request.getContextPath() );
      out.write("/member/memberUpdate\" method=\"post\" onsubmit=\"return fn_validation();\">\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>아이디</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"userId\" id=\"user_Id\" value=\"");
      out.print( m.getUserId() );
      out.write("\" readonly />  </td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("<!-- \t<tr>\r\n");
      out.write("\t\t<th>패스워드</th>\r\n");
      out.write("\t\t<td><input type=\"password\" name=\"password\" id=\"pass_Word\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>패스워드확인</th>\r\n");
      out.write("\t\t<td><input type=\"password\" name=\"password_chk\" id=\"pass_WordChk\" /></td>\r\n");
      out.write("\t</tr> -->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>이름</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"userName\" id=\"userName\" value=\"");
      out.print( m.getUserName() );
      out.write("\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>나이</th>\r\n");
      out.write("\t\t<td><input type=\"number\" name=\"age\" id=\"age\" value=\"");
      out.print( m.getAge() );
      out.write("\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>이메일</th>\r\n");
      out.write("\t\t<td><input type=\"email\" name=\"email\" id=\"email\" value=\"");
      out.print( m.getEmail() );
      out.write("\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>휴대폰</th>\r\n");
      out.write("\t\t<td><input type=\"tel\" id=\"phone\" name=\"phone\" value=\"");
      out.print( m.getPhone() );
      out.write("\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>주소</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"address\" id=\"address\"  value=\"");
      out.print( m.getAddress() );
      out.write("\"/></td>\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>성별</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" id=\"gender0\" value=\"M\" ");
 if(m.getGender().equals("M")){ 
      out.write("checked ");
 } 
      out.write(" />\r\n");
      out.write("\t\t\t<label for=\"gender0\">남</label>\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" id=\"gender1\" value=\"F\" ");
 if(m.getGender().equals("F")){ 
      out.write("checked ");
 } 
      out.write(" />\r\n");
      out.write("\t\t\t<label for=\"gender1\">여</label>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>취미</th>\r\n");
      out.write("\t\t<td><input type=\"checkbox\" name=\"hobby\" id=\"hobby1\"  value =\"운동\" ");
 if(Arrays.asList(hobbys).contains("운동")){
      out.write(" checked");
} 
      out.write("/>\r\n");
      out.write("\t\t<label for=\"hobby1\">운동</label>\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" id=\"hobby2\"  value =\"등산\" ");
 if(Arrays.asList(hobbys).contains("등산")){
      out.write(" checked");
} 
      out.write("/>\r\n");
      out.write("\t\t<label for=\"hobby2\">등산</label>\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" id=\"hobby3\"  value =\"독서\" ");
 if(Arrays.asList(hobbys).contains("독서")){
      out.write(" checked");
} 
      out.write("/>\r\n");
      out.write("\t\t<label for=\"hobby3\">독서</label>\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" id=\"hobby4\"  value =\"게임\"");
 if(Arrays.asList(hobbys).contains("게임")){
      out.write(" checked");
} 
      out.write("/>\r\n");
      out.write("\t\t<label for=\"hobby4\">게임</label>\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" id=\"hobby5\"  value =\"여행\"");
 if(Arrays.asList(hobbys).contains("여행")){
      out.write(" checked");
} 
      out.write("/>\r\n");
      out.write("\t\t<label for=\"hobby5\">여행</label>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>가입일</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"enroll\" id=\"enroll\"  value=\"");
      out.print( m.getEnrollDate() );
      out.write("\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t</tr>\t\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"submit\" value=\"수정\" />\r\n");
      out.write("<input type=\"reset\" value=\"초기화\" />\r\n");
      out.write("<input type=\"button\" value=\"비밀번호변경\" onclick=\"fn_update_password()\"/>\r\n");
      out.write("<input type=\"button\" value=\"탈퇴하기\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/member/memberDelete'\" />\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"updatePasswordFrm\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"userId\" id=\"userIds\"/>\r\n");
      out.write("</form>\r\n");
      out.write("\t\t\r\n");
      out.write("<script>\r\n");
      out.write("function fn_update_password(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar userId = $(\"#user_Id\").val().trim();\r\n");
      out.write("\t\r\n");
      out.write("\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/member/UpdatePassword\";\r\n");
      out.write("\tvar title = \"updatePassword\";\r\n");
      out.write("\tvar status = \"left=500px, top=200px, width=400px, height=210px\";\r\n");
      out.write("\tvar popup = window.open(url, title, status);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar updatePasswordFrm = document.updatePasswordFrm;\r\n");
      out.write("\tupdatePasswordFrm.userId.value = $(\"#user_Id\").val().trim();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tupdatePasswordFrm.target = title;\r\n");
      out.write("\tupdatePasswordFrm.action = url;\r\n");
      out.write("\tupdatePasswordFrm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t<footer>\r\n");
      out.write("\t\t\t<p>&lt;Copyright 2018. <strong>KH정보교육원</strong>. All rights reserved.&gt;</p>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
